"""Add column contact to store

Revision ID: fbae63af4e5d
Revises: 
Create Date: 2022-07-18 15:04:14.521490

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fbae63af4e5d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stores', sa.Column('contact', sa.String(), nullable=True))
    op.create_index(op.f('ix_stores_contact'), 'stores', ['contact'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_stores_contact'), table_name='stores')
    op.drop_column('stores', 'contact')
    # ### end Alembic commands ###
