"""Second revision

Revision ID: 6238e88d346a
Revises: e3997f47814d
Create Date: 2022-07-18 16:55:00.898569

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6238e88d346a'
down_revision = 'e3997f47814d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_university_id', table_name='university')
    op.drop_index('ix_university_name', table_name='university')
    op.drop_table('university')
    op.drop_index('ix_student_average', table_name='student')
    op.drop_index('ix_student_id', table_name='student')
    op.drop_index('ix_student_name', table_name='student')
    op.drop_table('student')
    op.drop_index('ix_course_id', table_name='course')
    op.drop_index('ix_course_name', table_name='course')
    op.drop_table('course')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('course',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=True),
    sa.Column('university', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['university'], ['university.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_course_name', 'course', ['name'], unique=False)
    op.create_index('ix_course_id', 'course', ['id'], unique=False)
    op.create_table('student',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=True),
    sa.Column('average', sa.INTEGER(), nullable=True),
    sa.Column('university', sa.INTEGER(), nullable=True),
    sa.Column('course', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['course'], ['course.id'], ),
    sa.ForeignKeyConstraint(['university'], ['university.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_student_name', 'student', ['name'], unique=False)
    op.create_index('ix_student_id', 'student', ['id'], unique=False)
    op.create_index('ix_student_average', 'student', ['average'], unique=False)
    op.create_table('university',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_university_name', 'university', ['name'], unique=False)
    op.create_index('ix_university_id', 'university', ['id'], unique=False)
    # ### end Alembic commands ###
