"""Test 2

Revision ID: 6724da4e6e68
Revises: e88442c01392
Create Date: 2022-07-18 19:30:42.506640

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6724da4e6e68'
down_revision = 'e88442c01392'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_shoppings_address', table_name='shoppings')
    op.drop_index('ix_shoppings_id', table_name='shoppings')
    op.drop_index('ix_shoppings_name', table_name='shoppings')
    op.drop_table('shoppings')
    op.drop_index('ix_employees_id', table_name='employees')
    op.drop_index('ix_employees_name', table_name='employees')
    op.drop_table('employees')
    op.drop_index('ix_stores_id', table_name='stores')
    op.drop_index('ix_stores_name', table_name='stores')
    op.drop_table('stores')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stores',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=True),
    sa.Column('located_on', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['located_on'], ['shoppings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_stores_name', 'stores', ['name'], unique=False)
    op.create_index('ix_stores_id', 'stores', ['id'], unique=False)
    op.create_table('employees',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=True),
    sa.Column('working_on', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['working_on'], ['stores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_employees_name', 'employees', ['name'], unique=False)
    op.create_index('ix_employees_id', 'employees', ['id'], unique=False)
    op.create_table('shoppings',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=True),
    sa.Column('address', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_shoppings_name', 'shoppings', ['name'], unique=False)
    op.create_index('ix_shoppings_id', 'shoppings', ['id'], unique=False)
    op.create_index('ix_shoppings_address', 'shoppings', ['address'], unique=False)
    # ### end Alembic commands ###
